/**
 * Three-letter parish codes used on the East Sussex rights of way map
 * (https://row.eastsussex.gov.uk/). The open FeatureServer has Path_Name
 * only, so codes are keyed by the parish prefix of that name.
 * Keys match FeatureServer spellings, including the St Ann / St John variants.
 */
export const PARISH_CODE_BY_NAME: Record<string, string> = {
  Alciston: "ALC",
  Alfriston: "ALF",
  Arlington: "ARL",
  Ashburnham: "ASH",
  Barcombe: "BAR",
  Battle: "BAT",
  Beckley: "BEC",
  Beddingham: "BED",
  Berwick: "BER",
  Bexhill: "BEX",
  Bodiam: "BOD",
  Brede: "BRE",
  Brightling: "BRI",
  Burwash: "BUR",
  Buxted: "BUX",
  Camber: "CAM",
  Catsfield: "CAT",
  Chailey: "CHL",
  "Chalvington with Ripe": "CHV",
  Chiddingly: "CHD",
  Crowborough: "CRB",
  Crowhurst: "CRH",
  "Cuckmere Valley": "CMV",
  Dallington: "DAL",
  Danehill: "DAN",
  Ditchling: "DIT",
  "East Chiltington": "ECH",
  "East Dean and Friston": "EDF",
  "East Guldeford": "EGU",
  "East Hoathly with Halland": "EHH",
  Eastbourne: "EBN",
  Etchingham: "ETC",
  Ewhurst: "EWH",
  Fairlight: "FAI",
  Falmer: "FAL",
  Firle: "FIR",
  Fletching: "FLE",
  "Forest Row": "FOR",
  Framfield: "FRM",
  Frant: "FRT",
  Glynde: "GLY",
  Guestling: "GUE",
  "Hadlow Down": "HAD",
  Hailsham: "HAI",
  Hamsey: "HAM",
  Hartfield: "HAR",
  Hastings: "HAS",
  "Heathfield and Waldron": "HEA",
  Hellingly: "HEL",
  Herstmonceux: "HER",
  Hooe: "HOO",
  Horam: "HOR",
  "Hurst Green": "HUR",
  Icklesham: "ICK",
  Iden: "IDN",
  Iford: "IFD",
  Isfield: "ISF",
  "Kingston Near Lewes": "KIN",
  Laughton: "LAU",
  Lewes: "LEW",
  "Lewes Town Centre": "LTC",
  "Little Horsted": "LIT",
  "Long Man": "LON",
  Maresfield: "MAR",
  "Mayfield and Five Ashes": "MAY",
  Mountfield: "MOU",
  Newhaven: "NWV",
  Newick: "NWK",
  Ninfield: "NIN",
  Northiam: "NOR",
  Peacehaven: "PCV",
  Peasmarsh: "PSM",
  Penhurst: "PEN",
  Pett: "PET",
  Pevensey: "PEV",
  Piddinghoe: "PID",
  Playden: "PLA",
  Plumpton: "PLU",
  Polegate: "POL",
  Ringmer: "RIN",
  Rodmell: "ROD",
  Rotherfield: "ROT",
  Rye: "RYE",
  "Rye Foreign": "RYF",
  "Rye Town Centre": "RTC",
  "Salehurst and Robertsbridge": "SAL",
  Seaford: "SEA",
  Sedlescombe: "SED",
  Selmeston: "SEL",
  "South Heighton": "SOH",
  Southease: "SOE",
  "St. Ann (Without)": "SAW",
  "St John Without": "SJW",
  "St. John (Without)": "SJW",
  Streat: "STR",
  "Tarring Neville": "TAR",
  Telscombe: "TEL",
  Ticehurst: "TIC",
  Uckfield: "UCK",
  Udimore: "UDI",
  Wadhurst: "WAD",
  Warbleton: "WRB",
  Wartling: "WRT",
  Westfield: "WSF",
  Westham: "WSH",
  Westmeston: "WSM",
  Whatlington: "WHA",
  "Willingdon and Jevington": "WIL",
  Withyham: "WIT",
  Wivelsfield: "WIV",
};

const PARISH_CODE_BY_NORMALIZED_NAME = new Map(
  Object.entries(PARISH_CODE_BY_NAME).map(([name, code]) => [
    name.toLowerCase(),
    code,
  ]),
);

export function parishCode(parish: string): string | undefined {
  return PARISH_CODE_BY_NORMALIZED_NAME.get(parish.trim().toLowerCase());
}
